---
title: "Analyzing the Influence of Gender and Age on Shelter Return numbers in Toronto In 2023"
author: 
  - Xuecheng Gao
thanks: "https://github.com/XuechengGao/Shelter_Return_numbers_in_Toronto_2023.git"
date: today
date-format: long
abstract: "This study examines the impact of gender and age on Toronto shelter return numbers in 2023. We used linear regression to analyze data from shelter records to examine the relationship between gender, age, and shelter returns. The study found significant correlations between gender, age demographics and housing return rates. These results illustrate the importance of considering gender and age demographics in addressing homelessness in the Toronto region."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false
#### Workspace setup ####
library(ggplot2)
library(arrow)
library(scales)
library(modelsummary)
library(tidyverse)
library(rstanarm)
library(knitr)
library(here)
library(marginaleffects)
```


# Introduction

Homelessness is a serious social problem. Toronto, as one of the important cities in Canada, has established many comprehensive shelters in response to this problem. These shelters provide support and temporary accommodation to homeless individuals. The problem of homelessness can be studied through the data recorded by these shelters.

The purpose of this study is to explore the impact of gender and age on shelter system utilization in Toronto in 2023. Data comes from the Shelter Management Information System (SMIS), which collects a variety of information including shelter locations, homeless information, and more. Through data analysis, I found that gender and age are important factors that may affect homelessness. Understanding the relationship between these factors and shelter can inform and inform targeted interventions for the different needs of different population groups. A deeper understanding of homelessness in Toronto can be gained by analyzing the relationship between gender, age, and housing returns.


# Data {#sec-data}

## Data Source




## Data clean


## Methodology


## Variables



# Model



## Model set-up

## Model Justification

# Results {#sec-results}



# Discussion {#sec-discussion}

## First discussion point {#sec-first-point}


## Second discussion point

## Third discussion point

## Weaknesses and next steps


\newpage

\appendix

# Appendix {-}


# Additional data details

# Model details {#sec-model-details}



\newpage


# References


